services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: network_db
    ports:
      - "5432:5432"

  worker:
    build: .
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate --noinput &&
             celery -A network_coverage worker --loglevel=info"

  beat:
    build: .
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate --noinput &&
             celery -A network_coverage beat --loglevel=info"

volumes:
  static_volume:
